paper_api_version=1.21.11-R0.1-SNAPSHOT
bukkit_api_version=1.21
java_version=21

maven_group=org.pynnccnskneuow.mtauctionhouse
archives_base_name=mtauctionhouse
plugin_version=1.0
plugin_description=Custom Auction House for secure player item sales
main_class=org.pynnccnskneuow.mtauctionhouse.PGPlugin

org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
